services:
  - type: web
    name: hubstree-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node src/backend/server.js"
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
